{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"name":"MFCC.ipynb","provenance":[],"mount_file_id":"1MPLJYBOQu0LKLOagLOOdRuAwqW2klcDE","authorship_tag":"ABX9TyM6WzKAwg/izaxC+x5asovS"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"code","metadata":{"id":"cc7PZaHoV4oI","executionInfo":{"status":"ok","timestamp":1627446160748,"user_tz":-330,"elapsed":493,"user":{"displayName":"Arya Bhattacharyya","photoUrl":"","userId":"02886052585458379523"}}},"source":["import os\n","import boto3\n"],"execution_count":1,"outputs":[]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/","height":693},"id":"GSSjSF-yV8-J","executionInfo":{"status":"ok","timestamp":1627446080882,"user_tz":-330,"elapsed":3728,"user":{"displayName":"Arya Bhattacharyya","photoUrl":"","userId":"02886052585458379523"}},"outputId":"9daf7570-97b3-49cb-b685-bdc72d23fbe3"},"source":["pip install librosa\n"],"execution_count":3,"outputs":[{"output_type":"stream","text":["Requirement already satisfied: librosa in /usr/local/lib/python3.7/dist-packages (0.8.1)\n","Requirement already satisfied: scikit-learn!=0.19.0,>=0.14.0 in /usr/local/lib/python3.7/dist-packages (from librosa) (0.22.2.post1)\n","Requirement already satisfied: joblib>=0.14 in /usr/local/lib/python3.7/dist-packages (from librosa) (1.0.1)\n","Requirement already satisfied: resampy>=0.2.2 in /usr/local/lib/python3.7/dist-packages (from librosa) (0.2.2)\n","Requirement already satisfied: numba>=0.43.0 in /usr/local/lib/python3.7/dist-packages (from librosa) (0.51.2)\n","Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from librosa) (1.4.1)\n","Requirement already satisfied: numpy>=1.15.0 in /usr/local/lib/python3.7/dist-packages (from librosa) (1.19.5)\n","Requirement already satisfied: pooch>=1.0 in /usr/local/lib/python3.7/dist-packages (from librosa) (1.4.0)\n","Requirement already satisfied: soundfile>=0.10.2 in /usr/local/lib/python3.7/dist-packages (from librosa) (0.10.3.post1)\n","Requirement already satisfied: decorator>=3.0.0 in /usr/local/lib/python3.7/dist-packages (from librosa) (4.4.2)\n","Requirement already satisfied: audioread>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from librosa) (2.1.9)\n","Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.7/dist-packages (from librosa) (21.0)\n","Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from numba>=0.43.0->librosa) (57.2.0)\n","Requirement already satisfied: llvmlite<0.35,>=0.34.0.dev0 in /usr/local/lib/python3.7/dist-packages (from numba>=0.43.0->librosa) (0.34.0)\n","Requirement already satisfied: pyparsing>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging>=20.0->librosa) (2.4.7)\n","Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from pooch>=1.0->librosa) (2.23.0)\n","Requirement already satisfied: appdirs in /usr/local/lib/python3.7/dist-packages (from pooch>=1.0->librosa) (1.4.4)\n","Requirement already satisfied: six>=1.3 in /usr/local/lib/python3.7/dist-packages (from resampy>=0.2.2->librosa) (1.15.0)\n","Requirement already satisfied: cffi>=1.0 in /usr/local/lib/python3.7/dist-packages (from soundfile>=0.10.2->librosa) (1.14.6)\n","Requirement already satisfied: pycparser in /usr/local/lib/python3.7/dist-packages (from cffi>=1.0->soundfile>=0.10.2->librosa) (2.20)\n","Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->pooch>=1.0->librosa) (3.0.4)\n","Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1\n","  Downloading urllib3-1.25.11-py2.py3-none-any.whl (127 kB)\n","\u001b[K     |████████████████████████████████| 127 kB 4.4 MB/s \n","\u001b[?25hRequirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->pooch>=1.0->librosa) (2.10)\n","Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->pooch>=1.0->librosa) (2021.5.30)\n","Installing collected packages: urllib3\n","  Attempting uninstall: urllib3\n","    Found existing installation: urllib3 1.26.6\n","    Uninstalling urllib3-1.26.6:\n","      Successfully uninstalled urllib3-1.26.6\n","\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n","datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.\u001b[0m\n","Successfully installed urllib3-1.25.11\n"],"name":"stdout"},{"output_type":"display_data","data":{"application/vnd.colab-display-data+json":{"pip_warning":{"packages":["urllib3"]}}},"metadata":{"tags":[]}}]},{"cell_type":"code","metadata":{"id":"s0UrzBVDWE8X","executionInfo":{"status":"ok","timestamp":1627446171165,"user_tz":-330,"elapsed":3596,"user":{"displayName":"Arya Bhattacharyya","photoUrl":"","userId":"02886052585458379523"}}},"source":["import librosa"],"execution_count":2,"outputs":[]},{"cell_type":"code","metadata":{"id":"fiqHbgmDXEbc","executionInfo":{"status":"ok","timestamp":1627446501901,"user_tz":-330,"elapsed":738,"user":{"displayName":"Arya Bhattacharyya","photoUrl":"","userId":"02886052585458379523"}}},"source":["import numpy as np\n","from librosa import display"],"execution_count":3,"outputs":[]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"_vqbh535WcTr","executionInfo":{"status":"ok","timestamp":1627454081691,"user_tz":-330,"elapsed":2361229,"user":{"displayName":"Arya Bhattacharyya","photoUrl":"","userId":"02886052585458379523"}},"outputId":"4e54cc29-a7f0-4694-e42d-41ec79bd2af5"},"source":["#Loop to generate all the spectrograms\n","for i in range (301,345):\n","  audio_file=r\"/content/drive/MyDrive/Depression_Detection/Healthy_People_Audio/AIC_\"+str(i)+\"_result.mp3\"\n","  y,sr=librosa.load(audio_file)\n","  mfcc_features=librosa.feature.mfcc(y=y,sr=sr)\n","  import matplotlib.pyplot as plt\n","  fig, ax = plt.subplots()\n","  img = display.specshow(mfcc_features, x_axis='time', ax=ax)\n","  fig.colorbar(img, ax=ax)\n","  ax.set(title='MFCC')\n","  savename=r\"/content/drive/MyDrive/Depression_Detection/Healthy_People_Audio_MFCC/MFCC_AIC_\"+str(i)+\"_result.png\"\n","  fig.savefig(savename)  \n","  plt.close('all')"],"execution_count":5,"outputs":[{"output_type":"stream","text":["/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.\n","  warnings.warn(\"PySoundFile failed. Trying audioread instead.\")\n","/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.\n","  warnings.warn(\"PySoundFile failed. Trying audioread instead.\")\n","/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.\n","  warnings.warn(\"PySoundFile failed. Trying audioread instead.\")\n","/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.\n","  warnings.warn(\"PySoundFile failed. Trying audioread instead.\")\n","/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.\n","  warnings.warn(\"PySoundFile failed. Trying audioread instead.\")\n","/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.\n","  warnings.warn(\"PySoundFile failed. Trying audioread instead.\")\n","/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.\n","  warnings.warn(\"PySoundFile failed. Trying audioread instead.\")\n","/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.\n","  warnings.warn(\"PySoundFile failed. Trying audioread instead.\")\n","/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.\n","  warnings.warn(\"PySoundFile failed. Trying audioread instead.\")\n","/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.\n","  warnings.warn(\"PySoundFile failed. Trying audioread instead.\")\n","/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.\n","  warnings.warn(\"PySoundFile failed. Trying audioread instead.\")\n","/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.\n","  warnings.warn(\"PySoundFile failed. Trying audioread instead.\")\n","/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.\n","  warnings.warn(\"PySoundFile failed. Trying audioread instead.\")\n","/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.\n","  warnings.warn(\"PySoundFile failed. Trying audioread instead.\")\n","/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.\n","  warnings.warn(\"PySoundFile failed. Trying audioread instead.\")\n","/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.\n","  warnings.warn(\"PySoundFile failed. Trying audioread instead.\")\n","/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.\n","  warnings.warn(\"PySoundFile failed. Trying audioread instead.\")\n","/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.\n","  warnings.warn(\"PySoundFile failed. Trying audioread instead.\")\n","/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.\n","  warnings.warn(\"PySoundFile failed. Trying audioread instead.\")\n","/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.\n","  warnings.warn(\"PySoundFile failed. Trying audioread instead.\")\n","/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.\n","  warnings.warn(\"PySoundFile failed. Trying audioread instead.\")\n","/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.\n","  warnings.warn(\"PySoundFile failed. Trying audioread instead.\")\n","/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.\n","  warnings.warn(\"PySoundFile failed. Trying audioread instead.\")\n","/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.\n","  warnings.warn(\"PySoundFile failed. Trying audioread instead.\")\n","/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.\n","  warnings.warn(\"PySoundFile failed. Trying audioread instead.\")\n","/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.\n","  warnings.warn(\"PySoundFile failed. Trying audioread instead.\")\n","/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.\n","  warnings.warn(\"PySoundFile failed. Trying audioread instead.\")\n","/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.\n","  warnings.warn(\"PySoundFile failed. Trying audioread instead.\")\n","/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.\n","  warnings.warn(\"PySoundFile failed. Trying audioread instead.\")\n","/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.\n","  warnings.warn(\"PySoundFile failed. Trying audioread instead.\")\n","/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.\n","  warnings.warn(\"PySoundFile failed. Trying audioread instead.\")\n","/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.\n","  warnings.warn(\"PySoundFile failed. Trying audioread instead.\")\n","/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.\n","  warnings.warn(\"PySoundFile failed. Trying audioread instead.\")\n","/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.\n","  warnings.warn(\"PySoundFile failed. Trying audioread instead.\")\n","/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.\n","  warnings.warn(\"PySoundFile failed. Trying audioread instead.\")\n","/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.\n","  warnings.warn(\"PySoundFile failed. Trying audioread instead.\")\n","/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.\n","  warnings.warn(\"PySoundFile failed. Trying audioread instead.\")\n","/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.\n","  warnings.warn(\"PySoundFile failed. Trying audioread instead.\")\n","/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.\n","  warnings.warn(\"PySoundFile failed. Trying audioread instead.\")\n","/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.\n","  warnings.warn(\"PySoundFile failed. Trying audioread instead.\")\n","/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.\n","  warnings.warn(\"PySoundFile failed. Trying audioread instead.\")\n","/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.\n","  warnings.warn(\"PySoundFile failed. Trying audioread instead.\")\n","/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.\n","  warnings.warn(\"PySoundFile failed. Trying audioread instead.\")\n","/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.\n","  warnings.warn(\"PySoundFile failed. Trying audioread instead.\")\n"],"name":"stderr"}]},{"cell_type":"code","metadata":{"id":"qED0VBZvXuXb"},"source":[""],"execution_count":null,"outputs":[]}]}